### ISSUE TITLE
Request to Add support for hive datatypes

### ISSUE THREAD

**Issue by swathi9488** [yahoo/validatar#1]
The usecase that doesn't seem to work is the following:

I want to assert that sum of two hive columns equals the third column. 
For example in the yaml:
.
.
.
tests:
   - name: Verifies Callback relation
     description: Verifies the count of total callbacks =  failures + successes
     asserts:
        - Q.total_calls == Q.total_failed + Q.total_success

Here, total_calls, total_success and total_failed are all BIGINT. This assert fails. 
Could you please add support for recognizing datatypes while doing these kind of operations?

Thanks,
Swathi

**Comment by akshaisarma** [comment]
Sure! Thanks for reporting it.

Just to document the workaround for now: 

```
    asserts: - approx(Q.total_calls, (Q.total_failed + Q.total_success), 0.00001)
```

**Comment by akshaisarma** [comment]
We will solve it more generally and add support for data types from a Engine and perform type validation when asserting.

**Comment by akshaisarma** [comment]
FYI, https://github.com/yahoo/validatar/pull/5 has been merged in. We'll build a internal package for Yahoo and update the issue. You can try the jar from source if interested. Do a make jar after checking out the repo and use the target/validatar*-jar-with-dependencies.jar. You need maven.

**Comment by akshaisarma** [comment]
It has been released internally too.
