### ISSUE TITLE
Switch eval engine to JS Nashorn

### ISSUE THREAD

**Issue by joshwalters** [yahoo/validatar#15]
The evaluation engine for asserts could be switched to js/nashorn. This would allow for custom functions specified in an external js file to provide things like fuzzy matches, or whatever else is needed by the tester. A set of default functions could be provided.

**Comment by akshaisarma** [comment]
While it's a good idea and we should think of how we can use this to maybe just get the custom functions in, we lose all benefits of our "strong" typing by using JS.
