### ISSUE TITLE
Accept multiple files/folders as test suite

### ISSUE THREAD

**Issue by JianbaoTao** [yahoo/validatar#23]
Suppose I have the following file structure.
top/
    - X/a.yaml
    - X/b.yaml
    - c.yaml
    - d.yaml

Now I want to run tests in a.yaml, b.yaml, and c.yaml, but not in d.yaml. Currently validatar doesn't support that.

**Comment by akshaisarma** [comment]
Why not just have X/{a.yaml, b.yaml, c.yaml} and pass in X as the folder? Is there any reason why c.yaml must be outside?

**Comment by JianbaoTao** [comment]
Yes. Now suppose we have another folder Y in parallel with X, which, say, has e.yaml and f.yaml test files, and the c.yaml contains common tests for both X and Y. However, the tests for X (a, b, c) and the tests for Y (e, f, c) are run separately. You can't do that right now. That's why for my request.

**Comment by akshaisarma** [comment]
I think it's simpler and cleaner for you to copy c.yaml into X and Y rather than validatar take on the complexity on managing multiple input locations. Alternatively, you could invoke validatar on X and then separately on c.
