### ISSUE TITLE
Getting error as "UnsupportedClassVersionError:

### ISSUE THREAD

**Issue by ShubhangiSGaikwad** [yahoo/validatar#38]
On execution of command below : Getting exception .Need help to resolve this error.

**Command:**
[root@mac122 validatar-master]# hadoop jar validatar-0.5.5-jar-with-dependencies.jar com.yahoo.validatar.App -s tests/ --report report.xml --hive-jdbc jdbc:hive2://1XX.XX.XX.XX:10002

**Exception:**
"Exception in thread "main" java.lang.UnsupportedClassVersionError: com/yahoo/validatar/App : Unsupported major.minor version 52.0"

**Environment:**
1.)Hadoop 2.6.0-cdh5.8.2
2.)validatar-0.5.5

**Comment by akshaisarma** [comment]
Use JRE 8

**Comment by ShubhangiSGaikwad** [comment]
Hello Akshai,
I am a newbie to Java and Big Data Validatar.

As suggested I am running the big data validatar where Java8 is installed.On running using "java cp ...." command  , I am getting error as below related to class :
[root@mac64 java]# java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

[root@mac64 java]# echo $JAVA_HOME
/usr/lib/jvm/java-1.8.0-openjdk.x86_64

[root@mac64 java]# java -cp /home/validatar-validatar-0.5.5_125_old/validatar-validatar-0.5.5/ com.yahoo.validatar.AppTest
**Error: Could not find or load main class com.yahoo.validatar.AppTest**
[root@mac64 java]#

Note this machine is not part of the hadoop cluster.

Request to please help me in this.

**Comment by akshaisarma** [comment]
We simply do not have the time to teach folks Java or how to debug basic Java issues. Please follow one of the many, many online guides to do that.

If it reports that this main class is not being found, you should double check the class name you're passing it. Our main class is: ```com.yahoo.validatar.App``` not ```com.yahoo.validatar.AppTest```.
